### ISSUE TITLE
Errata?

### ISSUE THREAD

**Issue by Taariqq** [spbooks/sql1#1]
Hi Guys, 

Is the errata of the book available somewhere?

**Comment by simonmackie** [comment]
Hi Tariq, this is a very old book. The errata page has been lost along the way, unfortunately. I'll see if I can find it.

**Comment by Taariqq** [comment]
> Hi Tariq, this is a very old book. The errata page has been lost along the way, unfortunately. I'll see if I can find it.

Hi Simon,
Don't worry. I got it touch with Rudy and he was kind enough to offer to answer my question over twitter.
Reason I am starting out with this book is because this is the only resource I know that takes into consideration two important things. _a_) A new person does not want to be bogged down by the nuances of 'creating' tables when in fact they just want to learn to practice DML. And _b_) the books explains very well the order of execution and parsing. Very helpful.

**Comment by simonmackie** [comment]
Ok, thanks for letting me know. I'm glad that you are finding the book useful!
